# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen
theme: advanced
plugins:
 - emotions
 - paste
 - table
 - fullscreen
language: zh
paste_convert_headers_to_strong: true
paste_convert_middot_lists: true
paste_remove_spans: true
paste_remove_styles: true
paste_strip_class_attributes: true
theme: advanced
theme_advanced_toolbar_align: left
theme_advanced_toolbar_location: top
theme_advanced_buttons1: bold,italic,underline,forecolor,backcolor,undo,redo,emotions,link,unlink,numlist,bullist,outdent,indent,blockquote,justifyleft,justifycenter,justifyright,table,removeformat,cleanup,fullscreen
theme_advanced_buttons2: ''
theme_advanced_buttons3: ''
